fix: ensure ticket status remains as 'new' after escalation
pluginsGLPI/escalade pull request #158
Opened 2023-12-19 16:02 UTC by ccailly

!30921

## Description

This PR addresses a bug in the plugin where tickets would automatically change to the status 'in progress' after an escalation task, even when the desired configuration was set to 'new'. The issue was due to the group assignment altering the status.

## Changes

The fix involves a small change in the `ticket.form.php` file. A condition has been added to check if the last status of the ticket was 'incoming' and if the current status is 'incoming'. If both conditions are met, the `_from_object` key is set to true in the group ticket additional data variable. This key indicates to the add method that the status should not be altered during the group assignment.

2023-12-21 09:47 UTC, stonebuzz requested changes
I may have missed something, but it doesn't seem to work.

![image](https://github.com/pluginsGLPI/escalade/assets/7335054/23aba914-232c-4df4-b51f-e6c604ad082b)

![image](https://github.com/pluginsGLPI/escalade/assets/7335054/46d297fb-25a5-403f-a80b-706e808fb0e6)

My configuration

![image](https://github.com/pluginsGLPI/escalade/assets/7335054/b23cb61d-755a-435b-b584-3054df9c9ea8)

2023-12-21 10:07 UTC, stonebuzz commented
After modifying my configuration to match the original issue

![image](https://github.com/pluginsGLPI/escalade/assets/7335054/f44448c4-4b92-4f5a-9cb3-b469233a880c)

If I escalate a ticket with ```incoming``` status, the ```incoming``` status is retained.

But  If I escalate a ticket with ```inprogess``` status, the ```inprogess``` status is retained.

for me it doesn't matter what the original status is, the configured status should always be applied

2023-12-21 10:09 UTC, stonebuzz commented
another point (to be fixed via this PR)
The "do not change" option doesn't work (see my first comment)

2024-01-23 09:22 UTC, stonebuzz commented
Using escalation here does not retain "new" status

![image](https://github.com/pluginsGLPI/escalade/assets/7335054/af6b14e6-1b4d-428b-882a-e0b0491212fe)

From ```timeline``` action  or from the actors form it's ok =)

![image](https://github.com/pluginsGLPI/escalade/assets/7335054/5bb9a9ea-9be0-42ca-9861-6353f019add3)

2024-01-23 09:22 UTC, stonebuzz requested changes
See my previous comment

2024-01-23 16:14 UTC, AdrienClairembault requested changes

2024-01-23 16:14 UTC, AdrienClairembault commented on front/ticket.form.php
> +            $previous_ticket_status = (new Ticket())->getById($tickets_id)->fields['status'];
`getById` is a static method, we do not need to use `new` here:

```suggestion
            $previous_ticket_status = Ticket::getById($tickets_id)->fields['status'];
```

2024-01-24 09:30 UTC, AdrienClairembault requested changes
If I escalate a ticket with the "new" status and I've configurated the plugin to keep the status as "new", the `takeintoaccount` metric is triggered:

![image](https://github.com/pluginsGLPI/escalade/assets/42734840/7bd69b13-2692-465b-9d04-96b9ead1c019)

![image](https://github.com/pluginsGLPI/escalade/assets/42734840/ef0cecf7-eedf-4fc9-b378-6caa57b794d2)

Would this be a problem @stonebuzz ? I have difficulties understanding this plugin expected behaviors

2024-01-29 09:26 UTC, closed without merging