fix(Core): fix behavior from 'status' option
pluginsGLPI/escalade pull request #164
Opened 2024-01-26 09:02 UTC by stonebuzz

Replace https://github.com/pluginsGLPI/escalade/pull/158

Fix behavior for ```Ticket status after an escalation```	

```Do not Change``` and other status are apllied.

The final problem concerns ```SLAs```
When status is  ```new``` the ```take into account is computed``` (they shouldn't be).

2024-01-26 10:50 UTC, ccailly commented
The behaviors are good when I climb from the timeline button or from the climbing history, but when I climb by modifying the group directly from the assignation list, the status changes to `Processing` and doesn't stay at `New`.

2024-01-26 14:04 UTC, ccailly approved these changes

2024-01-29 09:12 UTC, AdrienClairembault approved these changes

2024-02-21 13:50 UTC, stonebuzz commented on inc/ticket.class.php
> +         $group_ticket_input['_from_object']['_do_not_compute_status'] = true;
This prevents GLPI from updating the status itself (according to hard-coded management rules, e.g. assignment -> "ASSIGNED" status).

2024-02-21 14:52 UTC, Rom1-B commented on inc/ticket.class.php
> +         $group_ticket_input['_from_object']['_do_not_compute_status'] = true;
Your proposal works, what I mean is that in the IF (before ELSE) you can avoid loading the ticket to retrieve its status and return the same value.

2024-02-21 15:57 UTC, Rom1-B requested changes

2024-02-21 16:12 UTC, Rom1-B approved these changes

2024-02-21 16:12 UTC, Rom1-B commented on inc/ticket.class.php
> +         if ($_SESSION['plugins']['escalade']['config']['ticket_last_status'] != -1){ // no change
```suggestion
         if ($_SESSION['plugins']['escalade']['config']['ticket_last_status'] != -1){
```

2024-03-11 10:58 UTC, merged