Fix user deletion lock
pluginsGLPI/escalade pull request #197
Opened 2024-05-21 07:53 UTC by Lainow

With this option, the delete button on the actor is considered deleted when you try to delete it. However, ol is indicated in the configuration that the delete button is displayed for users assigned to the ticket, but not for groups.
![image](https://github.com/pluginsGLPI/escalade/assets/107540223/e9ab82b6-1bb7-4c46-adfa-cb39144e2d03)

**Before**
![image](https://github.com/pluginsGLPI/escalade/assets/107540223/ab57df8e-6f05-4e51-bd56-b24b9f8a22bd)

**After**
![image](https://github.com/pluginsGLPI/escalade/assets/107540223/7d70a3ec-3717-423d-b7e0-5fb66622e0e9)

2024-05-21 09:45 UTC, stonebuzz requested changes

2024-05-21 09:45 UTC, stonebuzz commented on inc/ticket.class.php
> +                $item->input['_actors'] = $item->fields['_actors'] ?? '';
Wouldn't that be an array?

2024-05-21 09:49 UTC, Rom1-B commented on inc/ticket.class.php
> +                $item->input['_actors'] = $item->fields['_actors'] ?? '';
`_actors` is supposed to be an array?
```suggestion
                $item->input['_actors'] = $item->fields['_actors'] ?? [];
```

2024-05-21 09:54 UTC, stonebuzz commented
waiting for customer feedback

2024-05-28 09:55 UTC, Lainow commented
> waiting for customer feedback

According to customer feedback, the solution works well.

2024-05-28 11:24 UTC, Rom1-B approved these changes

2024-05-28 11:31 UTC, merged