Set assign as observer unchecked by default
pluginsGLPI/escalade pull request #203
Opened 2024-06-07 07:36 UTC by RomainLvr

The customer requests that the “Assign me as observer” box be unchecked by default.
![image](https://github.com/pluginsGLPI/escalade/assets/102067890/5a576f0a-a14d-4bb3-8047-90a2b8c7bee5)

Related ticket : 33253

2024-06-07 08:33 UTC, Rom1-B requested changes
We're very likely to get the opposite demand: people who want it checked by default.
In this case, we'll need a new parameter.

2024-06-07 09:28 UTC, RomainLvr commented
> We're very likely to get the opposite demand: people who want it checked by default. In this case, we'll need a new parameter.

Sorry for the mistake, it's all done 1cdbadd :+1:

2024-06-10 07:27 UTC, AdrienClairembault approved these changes

2024-06-10 07:44 UTC, Rom1-B approved these changes

2024-06-10 07:44 UTC, merged