Fix escalation history
pluginsGLPI/escalade pull request #222
Opened 2024-07-25 09:46 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33742

Fixed the fact that the escalation history no longer appeared when the assigned groups were changed from the ticket form.

2024-07-25 14:53 UTC, Rom1-B requested changes

2024-07-25 14:53 UTC, Rom1-B commented on inc/ticket.class.php
> +        $actors_count = 0;
It will be safer to compare the list of groups than to just count.

2024-07-30 07:39 UTC, Rom1-B approved these changes
Seems OK

2024-07-30 09:01 UTC, AdrienClairembault approved these changes

2024-07-31 06:54 UTC, merged