Fix ticket read no right message
pluginsGLPI/escalade pull request #248
Opened 2024-09-24 10:07 UTC by Lainow

Issue : !34524

Fixed redirection to the ticket database page if you do not have access rights.

2024-09-25 08:21 UTC, stonebuzz commented on front/ticket.form.php
> +}
is really needed ?

2024-09-25 08:22 UTC, stonebuzz commented
can you adapt `CHANGELOG.md`

2024-09-25 08:54 UTC, stonebuzz requested changes

2024-09-25 08:54 UTC, stonebuzz commented on CHANGELOG.md
> +- Correction of the read no right message ticket and redirection
```suggestion
- Redirect user after escalation if he has no rights to the ticket
```

2024-09-26 05:48 UTC, Rom1-B approved these changes

2024-09-26 07:29 UTC, stonebuzz approved these changes

2024-09-26 07:31 UTC, stonebuzz commented
waiting for customer feedback

2024-10-14 09:30 UTC, Lainow commented
> waiting for customer feedback

!34524
The ticket has been resolved because the customer has not replied despite 3 reminders.

2024-11-28 08:21 UTC, stonebuzz commented
Hi @Lainow 

can you rebase (We are going to merge)

++

2024-11-28 12:51 UTC, stonebuzz requested changes

2024-11-28 12:51 UTC, stonebuzz commented on CHANGELOG.md
> +- Redirect user after escalation if he has no rights to the ticket
```suggestion
- Redirect users without ticket rights after escalation.
```

2024-11-28 14:34 UTC, stonebuzz approved these changes

2024-11-28 14:34 UTC, merged