Fix scope - only tickets are affected
pluginsGLPI/escalade pull request #267
Opened 2024-12-09 15:44 UTC by keguira

"Display delete button" affect only ticket form not the change and problem.

fixes #266

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have performed a self-review of my code.
- [ ] I have added tests (when available) that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #266 
- The "Display delete button" are only affecting the tickets

## Screenshots (if appropriate):

2024-12-10 07:42 UTC, stonebuzz commented
@keguira thanks for contribution

I'm not sure what to think, it seems like it's intentional to have the behavior on the change and problem since 2.2.2

https://github.com/pluginsGLPI/escalade/releases/tag/2.2.2

@Rom1-B what do you think?

for me this PR is legitimate

It would be necessary (not necessarily in this PR) to have a dedicated option for change and problem)

2024-12-10 07:43 UTC, stonebuzz approved these changes

2024-12-10 09:21 UTC, Rom1-B requested changes
It seems that the documentation was not updated, as this functionality is also supposed to work for changes and problems. Therefore, it would be better to fix this part rather than removing it only to reintroduce it later (which would likely involve undoing your changes). I believe this is the most efficient approach.

https://github.com/pluginsGLPI/escalade/commit/fd286fa9888207d81c1c425066bbef56276f174b?w=1#diff-497804e83ceb478d4b3ec788864fa8cf4268fec92f908da67f7c8918bb35ef0dR68

2025-05-20 07:58 UTC, stonebuzz commented
Hello,

As this PR hasn’t progressed in several months, we propose closing it to avoid keeping an inactive request open.

Removing the "Display delete button" functionality entirely for changes and problems seems premature. A more appropriate solution would be to introduce a configurable option per item type (ticket / change / problem), allowing more granular control.

Feel free to reopen or submit a new PR based on this direction if needed.

Best regards

2025-05-20 07:58 UTC, closed without merging